POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "test",
  "firstName": "test",
    "lastName": "test",
    "phone": "test",
    "email": "test",
    "city": "test",
    "password": "test"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/1

###
DELETE http://localhost:3000/api/users/1

###
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "phone": "phone",
    "email": "email"
}

###
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJ0ZXN0IiwiYWRtaW4iOjAsImlhdCI6MTcxMTQ2NjA0NiwiZXhwIjoxNzEyMDcwODQ2fQ.fh58sXe4Z0NNxqv0R2zG0yskGlJN6ZHQ0TtLStpGnXM

