name: Docker Build

on:
  pull_request:

jobs:
  buildx:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0
      id: buildx
      with:
        install: true
    - name: Build
      run: docker build . # will run buildx